# Gradle Properties

# Project settings
#org.gradle.java.home=
org.gradle.warning.mode=fail

# Parallel builds
org.gradle.parallel=true
org.gradle.workers.max=4

# Build cache
org.gradle.caching=true

# Daemon settings
org.gradle.daemon=true
org.gradle.daemon.idletimeout=10800000

# Version properties
java.version=17
mapstruct.version=1.5.5.Final
lombok.version=1.18.30
aws.sdk.version=2.21.0
spring.cloud.aws.version=3.0.0

